<%@ Page Language="VB" AutoEventWireup="false" CodeFile="Galerija.aspx.vb" Inherits="Galerija" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Galerija</title>
    <link href="PrviStil.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <p><h1>Galerija</h1>Savremena galerija Zrenjanin (osnovana 1962. godine) sakuplja, čuva, sistematski istražuje i izlaže dela jugoslovenske i srpske posleratne likovne umetnosti, nastala uglavnom u Umetničkoj koloniji u Ečki (osnovana 1956. godine). Politikom prikupljanja i obrazovanja zbirke, koja danas sadrži preko dve hiljade šesto umetničkih predmeta umetnika iz bivše Jugoslavije i inostranstva, nije omogućeno samo praćenje rada kolonije u Ečki već je dobijen pregled savremene likovne umetnosti Jugoslavije (i Srbije) od 1946. godine do danas. Do osnivanja Muzeja savremene umetnosti u Beogradu 1965. godine, Umetnička kolonija u Ečki bila je jedino mesto u Srbiji gde se reprezentativna produkcija jugoslovenske likovne umetnosti mogla videti na jednom mestu.<img vspace="15" hspace="20" align=right src=galerija2.jpg/>Fond Savremene galerije čine zbirka slika i akvarela, zbirka skulpture, objekata i instalacije, kabinet grafike (grafički listovi i crteži), zbirka novih medija (fotografije, video – radovi i dr.) i zbirka inostrane umetnosti (radovi izvedeni različitim tehnikama u različitim medijima inostranih autora koji su boravili i radili u Umetničkoj koloniji Ečka). Svojim značajem fond Savremene galerije Zrenjanin zahteva ozbiljno naučno-istorijsko istraživanje, muzeološku obradu, digitalizaciju i prezentaciju kroz tematske izložbe i stalnu postavku.Savremena galerija Zrenjanin deluje kroz različite sadržaje: organizovanje radionica za umetnike iz zemlje i inostranstva u Umetničkoj koloniji Ečka, organizovanje izložbi domaće i inostrane savremene umetnosti, organizovanje međunarodne manifestacije Bijenale akvarela.<img alt="Savremena galerija" vspace="15" hspace="20" align=left src=galerija3.jpg/>Sve izložbe u Salonu Savremene galerije propraćene su stručnim publikacijama u vidu kataloga. Izložbena delatnost praćena je i drugim aktivnostima: koncertima, promocijama knjiga, stručnim predavanjima.

Osnovni pravci delovanja Savremene galerije su davanje akcenta tematskim i studijskim izložbama koje komuniciraju suštinu zbirke Savremene galerije Zrenjanin, potenciranje naučne delatnosti i prenošenje znanja putem didaktičkih izložbi, ekspanzija izložbi vezanih za aktuelne tendencije u savremenoj umetnosti, kao i istraživanje novih metoda rada u oblasti vizuelne kulture, istorije i teorije umetnosti i muzeološke i kustoske prakse.Za svoj rad na aktivnom praćenju i dokumentovanju savremene umetničke produkcije na teritoriji bivše Jugoslavije i Srbije, kao i za muzeološki rad na fondu Savremene galerije Zrenjanin, njegovo prezentovanje kroz brojne tematske i didaktičke izložbe Savremena galerija Zrenjanin nagrađivana je više puta značajnim nagradama i priznanjima na državnom i lokalnom nivou(Priznanje Saveznog izvršnog veća 1963. godine, Nagrada Udruženja umetnika primenjenih umetnosti i dizajna Vojvodine, Novi Sad, 1979. godine, Vukova nagrada 1977. i Orden Vuka Karadžića 1999. godine, itd)je međunarodne manifestacije Bijenale akvarela.
Sve izložbe u Salonu Savremene galerije propraćene su stručnim publikacijama u vidu kataloga. Izložbena delatnost praćena je i drugim aktivnostima: koncertima, promocijama knjiga, stručnim predavanjima..
Realizacijom svojih programa Savremena galerija svom gradu donosi raznovrsnost i preporod na kulturnom planu kao i jačanju internacionalnog i multikulturalnog profila grada i sredine. Svojim programskim aktivnostima Savremena galerija Zrenjanin je postavla na zdrave osnove platformu za formiranje Muzeja savremene umetnosti u Zrenjaninu jer od svog osnivanja 1962. godine, odnosno od osnivanja Kolonije u Ečki 1956. vrši muzejsku delatnost te shodno tome neophodno je obezbetiti zgradu koja zadovoljava muzeološke kriterijume (namenski zidanu ili adaptiranu) u kojoj bi bili objedinjeni izložbeni prostor za aktuelne izložbe, prostor za stalnu postavku, depoi, radionice za konzervatore, stručna biblioteka i kancelarije za kustose i administraciju.
</p>
<div align="left"><p><a href=KulturaGrada.aspx><img src="BackButton.png" height="60" width="60"/></a></p></div>
</body>
</html>
